name: example_upgrade_dependencies_freezed
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation:
    path: ../../freezed_annotation

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.0
  json_serializable: ^6.9.1
  freezed:
    path: ../

dependency_overrides:
  freezed:
    path: ../
  freezed_annotation:
    path: ../../freezed_annotation

flutter:
  uses-material-design: true
